// Generated by CoffeeScript 2.7.0
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var board, cell, cells, checkWin, currentPlayer, gameOver, handleClick, i, len, results, status;
    currentPlayer = 'X';
    board = Array(9).fill(null);
    gameOver = false;
    cells = document.querySelectorAll('.cell');
    status = document.getElementById('status');
    checkWin = function() {
      var a, b, c, i, len, pattern, winPatterns;
      winPatterns = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
      for (i = 0, len = winPatterns.length; i < len; i++) {
        pattern = winPatterns[i];
        [a, b, c] = pattern;
        if (board[a] && board[a] === board[b] && board[a] === board[c]) {
          return board[a];
        }
      }
      if (board.every(function(cell) {
        return cell !== null;
      })) {
        return 'Draw';
      }
      return null;
    };
    handleClick = function(event) {
      var index, winner;
      index = event.target.dataset.cell;
      if (gameOver || board[index]) {
        return;
      }
      board[index] = currentPlayer;
      event.target.textContent = currentPlayer;
      winner = checkWin();
      if (winner) {
        gameOver = true;
        return status.textContent = winner === 'Draw' ? 'It\'s a draw!' : `${winner} wins!`;
      } else {
        return currentPlayer = currentPlayer === 'X' ? 'O' : 'X';
      }
    };
    results = [];
    for (i = 0, len = cells.length; i < len; i++) {
      cell = cells[i];
      results.push(cell.addEventListener('click', handleClick));
    }
    return results;
  });

}).call(this);
